/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import mvc_dao.ConnectDAO;
import Model.Agencias;
import javax.swing.JOptionPane;
//import java.sql.Connection;
//import java.sql.Statement;
/**
 *
 * @author Alunos
 */
public class JFAgencias extends javax.swing.JFrame {

    /**
     * Creates new form JFAgencias
     */
    public JFAgencias() {
        initComponents();
    }
    String operacaoAtivaGlobal = "Nenhum";
    
    /* Create new form */
     public JFAgencias(String operacaoGlobal) {
        initComponents();
        operacaoAtivaGlobal = operacaoGlobal;
        String operacao = "Incluir";
        
        if(operacaoAtivaGlobal.equals(operacao)){

            jTFNumAgencia.setVisible(true);
            jTFNomeAg.setVisible(true);
            jTFEndAgencia.setVisible(true);        
            jTFNumEndAgencia.setVisible(true);        
            jTFComplemento.setVisible(true);        
            jTFBairro.setVisible(true);
            jTFCidade.setVisible(true);        
            jTFUF.setVisible(true);        
            jTFCEP.setVisible(true);        
            jTFFone.setVisible(true);        
            

            jLBairro.setVisible(true); 
            jLCidade.setVisible(true); 
            jLComplemento.setVisible(true); 
            jLEndAgencia.setVisible(true);         
            jLFone.setVisible(true);         
            jLNumAgencia.setVisible(true);        
            jLNumEndAgencia.setVisible(true);         
            jLUF.setVisible(true);         
            jLCEP.setVisible(true);
            jLNomeAgencia.setVisible(true);
            jBConfirmar.setText("Incluir registro");        
        }
        
        
        operacaoAtivaGlobal = operacaoGlobal;
        
        String operacao1 = "Alterar";
        String operacao2 = "Consultar";
        String operacao3 = "Excluir";
        
        
        if(operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2) || operacaoAtivaGlobal.equals(operacao3)){

            
            jTFNumAgencia.setVisible(true);
            jTFNomeAg.setVisible(false);
            jTFEndAgencia.setVisible(false);        
            jTFNumEndAgencia.setVisible(false);        
            jTFComplemento.setVisible(false);        
            jTFBairro.setVisible(false);
            jTFCidade.setVisible(false);        
            jTFUF.setVisible(false);        
            jTFCEP.setVisible(false);        
            jTFFone.setVisible(false);        
            

            
            jLNumAgencia.setVisible(true); 
            jLBairro.setVisible(false); 
            jLCidade.setVisible(false); 
            jLComplemento.setVisible(false); 
            jLEndAgencia.setVisible(false);         
            jLFone.setVisible(false);                
            jLNumEndAgencia.setVisible(false);         
            jLUF.setVisible(false);         
            jLCEP.setVisible(false);
            jLNomeAgencia.setVisible(false);
            
            jBConfirmar.setText("Pesquisar registro");        
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jTFNumAgencia = new javax.swing.JTextField();
        jLNumAgencia = new javax.swing.JLabel();
        jLNomeAgencia = new javax.swing.JLabel();
        jTFNomeAg = new javax.swing.JTextField();
        jLEndAgencia = new javax.swing.JLabel();
        jTFEndAgencia = new javax.swing.JTextField();
        jTFNumEndAgencia = new javax.swing.JTextField();
        jLNumEndAgencia = new javax.swing.JLabel();
        jLComplemento = new javax.swing.JLabel();
        jTFComplemento = new javax.swing.JTextField();
        jLBairro = new javax.swing.JLabel();
        jTFBairro = new javax.swing.JTextField();
        jTFCidade = new javax.swing.JTextField();
        jLCidade = new javax.swing.JLabel();
        jLUF = new javax.swing.JLabel();
        jTFUF = new javax.swing.JTextField();
        jLCEP = new javax.swing.JLabel();
        jTFCEP = new javax.swing.JTextField();
        jLFone = new javax.swing.JLabel();
        jTFFone = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Testar Conexão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTFNumAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumAgenciaActionPerformed(evt);
            }
        });

        jLNumAgencia.setText("Número da agência:");

        jLNomeAgencia.setText("Nome da agência:");

        jTFNomeAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeAgActionPerformed(evt);
            }
        });

        jLEndAgencia.setText("Endereço da agência:");

        jTFEndAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEndAgenciaActionPerformed(evt);
            }
        });

        jTFNumEndAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumEndAgenciaActionPerformed(evt);
            }
        });

        jLNumEndAgencia.setText("Núm do end da agência:");

        jLComplemento.setText("Complemento:");

        jTFComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFComplementoActionPerformed(evt);
            }
        });

        jLBairro.setText("Bairro:");

        jTFBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFBairroActionPerformed(evt);
            }
        });

        jTFCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCidadeActionPerformed(evt);
            }
        });

        jLCidade.setText("Cidade:");

        jLUF.setText("UF:");

        jTFUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUFActionPerformed(evt);
            }
        });

        jLCEP.setText("CEP:");

        jTFCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCEPActionPerformed(evt);
            }
        });

        jLFone.setText("Fone:");

        jTFFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFoneActionPerformed(evt);
            }
        });

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLFone)
                                    .addComponent(jLCEP)
                                    .addComponent(jLUF)
                                    .addComponent(jLCidade)
                                    .addComponent(jLBairro)
                                    .addComponent(jLNomeAgencia)
                                    .addComponent(jLEndAgencia)
                                    .addComponent(jLNumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLNumEndAgencia)
                                    .addComponent(jLComplemento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFNumAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFNomeAg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFEndAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFNumEndAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFUF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumAgencia)
                    .addComponent(jTFNumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeAgencia)
                    .addComponent(jTFNomeAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndAgencia)
                    .addComponent(jTFEndAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumEndAgencia)
                    .addComponent(jTFNumEndAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLComplemento)
                    .addComponent(jTFComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBairro)
                    .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCidade)
                    .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUF)
                    .addComponent(jTFUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCEP)
                    .addComponent(jTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFone)
                    .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectDAO objcon = new ConnectDAO();
        objcon.connectDB();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFNumAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumAgenciaActionPerformed

    private void jTFNomeAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeAgActionPerformed

    private void jTFEndAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEndAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEndAgenciaActionPerformed

    private void jTFNumEndAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumEndAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumEndAgenciaActionPerformed

    private void jTFComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFComplementoActionPerformed

    private void jTFBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBairroActionPerformed

    private void jTFCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCidadeActionPerformed

    private void jTFUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUFActionPerformed

    private void jTFCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCEPActionPerformed

    private void jTFFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFoneActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao)){
            //criar o objeto dados_agencia
            Agencias dados_agencia = new Agencias();
            // Atribuir os dados da tela no novo objeto
            dados_agencia.setNum_age(Integer.parseInt(jTFNumAgencia.getText()));
            dados_agencia.setNome_age(jTFNomeAg.getText());
            dados_agencia.setEnde_age(jTFEndAgencia.getText());
            dados_agencia.setNume_age(jTFNumEndAgencia.getText());
            dados_agencia.setCompl_age(jTFComplemento.getText());
            dados_agencia.setBair_age(jTFBairro.getText());
            dados_agencia.setCida_age(jTFCidade.getText());
            dados_agencia.setUf_age(jTFUF.getText());
            dados_agencia.setCep_age(jTFCEP.getText());
            dados_agencia.setFone_age(jTFFone.getText());

        
            ConnectDAO objcon = new ConnectDAO();

            objcon.insereRegistroJFBD("AGENCIAS", dados_agencia.dadosSQLValues());

            jTFNumAgencia.setText("");
            jTFNomeAg.setText("");
            jTFEndAgencia.setText("");
            jTFNumEndAgencia.setText("");
            jTFComplemento.setText("");
            jTFBairro.setText("");
            jTFCidade.setText("");
            jTFCEP.setText("");
            jTFFone.setText("");
       }
        
        Agencias agencia_tela = new Agencias();
        operacao = "Alteracao";
        if (operacaoAtivaGlobal.equals(operacao)){
        ConnectDAO objcon = new ConnectDAO();
        Agencias dados_agencia = new Agencias();
            dados_agencia.setNum_age(Integer.parseInt(jTFNumAgencia.getText()));
            dados_agencia.setNome_age(jTFNomeAg.getText());
            dados_agencia.setEnde_age(jTFEndAgencia.getText());
            dados_agencia.setNume_age(jTFNumEndAgencia.getText());
            dados_agencia.setCompl_age(jTFComplemento.getText());
            dados_agencia.setBair_age(jTFBairro.getText());
            dados_agencia.setCida_age(jTFCidade.getText());
            dados_agencia.setUf_age(jTFUF.getText());
            dados_agencia.setCep_age(jTFCEP.getText());
            dados_agencia.setFone_age(jTFFone.getText());
            
            objcon.alteraRegistroJFBD("AGENCIAS",dados_agencia.alteraDadosSQLValues(),"NUM_AGE = " +jTFNumAgencia.getText());
            
            jTFNumAgencia.setText("");
            jTFNomeAg.setText("");
            jTFEndAgencia.setText("");
            jTFNumEndAgencia.setText("");
            jTFComplemento.setText("");
            jTFBairro.setText("");
            jTFCidade.setText("");
            jTFCEP.setText("");
            jTFFone.setText("");
        }
        
        //Agencias agencia_tela = new Agencias();
        operacao = "Alterar";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ConnectDAO objcon = new ConnectDAO();
            agencia_tela = objcon.pesquisaAgenciaJFBD("AGENCIAS","NUM_AGE = '" +jTFNumAgencia.getText()+ "'");
           
            
            jTFNumAgencia.setText(Integer.toString(agencia_tela.getNum_age()));
            jTFNomeAg.setText(agencia_tela.getNome_age());
            jTFEndAgencia.setText(agencia_tela.getEnde_age());
            jTFNumEndAgencia.setText(agencia_tela.getNume_age());
            jTFComplemento.setText(agencia_tela.getCompl_age());
            jTFBairro.setText(agencia_tela.getBair_age());
            jTFCidade.setText(agencia_tela.getCida_age());
            jTFUF.setText(agencia_tela.getUf_age());
            jTFCEP.setText(agencia_tela.getCep_age());
            jTFFone.setText(agencia_tela.getFone_age());
            
           
            jTFNomeAg.setVisible(true);
            jTFEndAgencia.setVisible(true);        
            jTFNumEndAgencia.setVisible(true);        
            jTFComplemento.setVisible(true);        
            jTFBairro.setVisible(true);
            jTFCidade.setVisible(true);        
            jTFUF.setVisible(true);        
            jTFCEP.setVisible(true);        
            jTFFone.setVisible(true);        
            
            /*
                Primeiro torna visível os jTextLabel
             */
            
            jLBairro.setVisible(true); 
            jLCidade.setVisible(true); 
            jLComplemento.setVisible(true); 
            jLEndAgencia.setVisible(true);         
            jLFone.setVisible(true);         
           
            jLNumEndAgencia.setVisible(true);         
            jLUF.setVisible(true);         
            jLCEP.setVisible(true);
            jLNomeAgencia.setVisible(true);
            
            
            jBConfirmar.setText("Alterar registro");
                  
            operacaoAtivaGlobal = "Alteracao";        
        }
        
        operacao = "Consultado";
        if (operacaoAtivaGlobal.equals(operacao)) {
            this.dispose();
        }
        
        
        operacao = "Excluido";
        if (operacaoAtivaGlobal.equals(operacao)) {
            int resposta = JOptionPane.showConfirmDialog(
            this, 
             "Tem certeza que deseja excluir esse Registro?", 
             "Confirmação", 
               JOptionPane.YES_NO_OPTION
            );
 
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFBD("AGENCIAS","NUM_AGE = '" +jTFNumAgencia.getText()+ "'");
                JOptionPane.showMessageDialog(this, "Registro excluído!");
                this.dispose();
            } else {
                this.dispose();
            }
        }
        
        
        String operacao1 = "Excluir";
        String operacao2 = "Consultar";
        
        if (operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2)) {
            ConnectDAO objcon = new ConnectDAO();
            agencia_tela = objcon.pesquisaAgenciaJFBD("AGENCIAS","NUM_AGE = '" +jTFNumAgencia.getText()+ "'");
           
            
            jTFNumAgencia.setText(Integer.toString(agencia_tela.getNum_age()));
            jTFNomeAg.setText(agencia_tela.getNome_age());
            jTFEndAgencia.setText(agencia_tela.getEnde_age());
            jTFNumEndAgencia.setText(agencia_tela.getNume_age());
            jTFComplemento.setText(agencia_tela.getCompl_age());
            jTFBairro.setText(agencia_tela.getBair_age());
            jTFCidade.setText(agencia_tela.getCida_age());
            jTFUF.setText(agencia_tela.getUf_age());
            jTFCEP.setText(agencia_tela.getCep_age());
            jTFFone.setText(agencia_tela.getFone_age());
            
           
            jTFNomeAg.setVisible(true);
            jTFEndAgencia.setVisible(true);        
            jTFNumEndAgencia.setVisible(true);        
            jTFComplemento.setVisible(true);        
            jTFBairro.setVisible(true);
            jTFCidade.setVisible(true);        
            jTFUF.setVisible(true);        
            jTFCEP.setVisible(true);        
            jTFFone.setVisible(true);   
            
            
            jTFNomeAg.setEditable(false);
            jTFEndAgencia.setEditable(false);        
            jTFNumEndAgencia.setEditable(false);        
            jTFComplemento.setEditable(false);        
            jTFBairro.setEditable(false);
            jTFCidade.setEditable(false);        
            jTFUF.setEditable(false);        
            jTFCEP.setEditable(false);        
            jTFFone.setEditable(false);        
            
            
            
            jLBairro.setVisible(true); 
            jLCidade.setVisible(true); 
            jLComplemento.setVisible(true); 
            jLEndAgencia.setVisible(true);         
            jLFone.setVisible(true);         
            jLNumEndAgencia.setVisible(true);         
            jLUF.setVisible(true);         
            jLCEP.setVisible(true);
            jLNomeAgencia.setVisible(true);
            
            
            jBConfirmar.setText("Fechar");
            
            if (operacaoAtivaGlobal.equals(operacao1)) {
            operacaoAtivaGlobal = "Excluido";
            jBConfirmar.setText("Excluir Registro");
            
            }
            else {
            operacaoAtivaGlobal = "Consultado";
            }
        }
        
        
        
    }//GEN-LAST:event_jBConfirmarActionPerformed
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAgencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCEP;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLEndAgencia;
    private javax.swing.JLabel jLFone;
    private javax.swing.JLabel jLNomeAgencia;
    private javax.swing.JLabel jLNumAgencia;
    private javax.swing.JLabel jLNumEndAgencia;
    private javax.swing.JLabel jLUF;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCEP;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFComplemento;
    private javax.swing.JTextField jTFEndAgencia;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFNomeAg;
    private javax.swing.JTextField jTFNumAgencia;
    private javax.swing.JTextField jTFNumEndAgencia;
    private javax.swing.JTextField jTFUF;
    // End of variables declaration//GEN-END:variables
}
