/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;   

import mvc_dao.ConnectDAO;
import Model.Cliente;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class JFCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFCliente
     */
    public JFCliente() {
        initComponents();
    }

    String operacaoAtivaGlobal = "Nenhum";

    /* Create new form */
     public JFCliente(String operacaoGlobal) {
        initComponents();
        operacaoAtivaGlobal = operacaoGlobal;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            
            JTFBairroCliente.setVisible(true);
            JTFCepCliente.setVisible(true);
            JTFCidadeCliente.setVisible(true);
            JTFCnpjCliente.setVisible(true);
            JTFComEndCliente.setVisible(true);
            JTFCpfCliente.setVisible(true);
            JTFDataNascCliente.setVisible(true);
            JTFEndCliente.setVisible(true);
            JTFIdCliente.setVisible(true);
            JTFNomeCliente.setVisible(true);
            JTFNumCliente.setVisible(true);
            JTFTelCliente.setVisible(true);
            JTFUfCliente.setVisible(true);
            
            jLBairroCliente.setVisible(true);
            jLCepCliente.setVisible(true);
            jLCidadeCliente.setVisible(true);
            jLComEndCliente.setVisible(true);
            jLCpfCliente.setVisible(true);
            jLDataNascCliente.setVisible(true);
            jLEndCliente.setVisible(true);
            jLIdCliente.setVisible(true);
            jLNomeCliente.setVisible(true);
            jLNumCliente.setVisible(true);
            jLTelCliente.setVisible(true);
            jLUfCliente.setVisible(true);
            jLCnpjCliente.setVisible(true);
            
            jBConfirmar.setText("Incluir registro");
            
    }
    
        operacaoAtivaGlobal = operacaoGlobal;
        
        String operacao1 = "Alterar";
        String operacao2 = "Consultar";
        String operacao3 = "Excluir";
        
         if(operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2) || operacaoAtivaGlobal.equals(operacao3)){
        
            JTFIdCliente.setVisible(true);
            JTFBairroCliente.setVisible(false);
            JTFCepCliente.setVisible(false);
            JTFCidadeCliente.setVisible(false);
            JTFCnpjCliente.setVisible(false);
            JTFComEndCliente.setVisible(false);
            JTFCpfCliente.setVisible(false);
            JTFDataNascCliente.setVisible(false);
            JTFEndCliente.setVisible(false);
            JTFNomeCliente.setVisible(false);
            JTFNumCliente.setVisible(false);
            JTFTelCliente.setVisible(false);
            JTFUfCliente.setVisible(false);
            
            jLIdCliente.setVisible(true);
            jLBairroCliente.setVisible(false);
            jLCepCliente.setVisible(false);
            jLCidadeCliente.setVisible(false);
            jLComEndCliente.setVisible(false);
            jLCpfCliente.setVisible(false);
            jLDataNascCliente.setVisible(false);
            jLEndCliente.setVisible(false);
            jLNomeCliente.setVisible(false);
            jLNumCliente.setVisible(false);
            jLTelCliente.setVisible(false);
            jLUfCliente.setVisible(false);
            jLCnpjCliente.setVisible(false);
            
            jBConfirmar.setText("Pesquisar registro");
        
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIdCliente = new javax.swing.JLabel();
        jLNomeCliente = new javax.swing.JLabel();
        jLEndCliente = new javax.swing.JLabel();
        jLNumCliente = new javax.swing.JLabel();
        jLComEndCliente = new javax.swing.JLabel();
        jLBairroCliente = new javax.swing.JLabel();
        jLCidadeCliente = new javax.swing.JLabel();
        jLUfCliente = new javax.swing.JLabel();
        jLCepCliente = new javax.swing.JLabel();
        jLTelCliente = new javax.swing.JLabel();
        jLCpfCliente = new javax.swing.JLabel();
        jLDataNascCliente = new javax.swing.JLabel();
        jLCnpjCliente = new javax.swing.JLabel();
        JTFIdCliente = new javax.swing.JTextField();
        JTFNomeCliente = new javax.swing.JTextField();
        JTFEndCliente = new javax.swing.JTextField();
        JTFNumCliente = new javax.swing.JTextField();
        JTFComEndCliente = new javax.swing.JTextField();
        JTFBairroCliente = new javax.swing.JTextField();
        JTFCidadeCliente = new javax.swing.JTextField();
        JTFUfCliente = new javax.swing.JTextField();
        JTFCepCliente = new javax.swing.JTextField();
        JTFTelCliente = new javax.swing.JTextField();
        JTFCpfCliente = new javax.swing.JTextField();
        JTFDataNascCliente = new javax.swing.JTextField();
        JTFCnpjCliente = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLIdCliente.setText("ID do Cliente:");

        jLNomeCliente.setText("Nome:");

        jLEndCliente.setText("Endereço:");

        jLNumCliente.setText("Número:");

        jLComEndCliente.setText("Complemento do Endereço:");

        jLBairroCliente.setText("Bairro:");

        jLCidadeCliente.setText("Cidade:");

        jLUfCliente.setText("UF:");

        jLCepCliente.setText("CEP:");

        jLTelCliente.setText("Telefone:");

        jLCpfCliente.setText("CPF:");

        jLDataNascCliente.setText("Data de nascimento:");

        jLCnpjCliente.setText("CNPJ:");

        JTFNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeClienteActionPerformed(evt);
            }
        });

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jButton1.setText("Testar Conexão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLIdCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEndCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNumCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLComEndCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(JTFComEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBairroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCidadeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLUfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFUfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCepCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTelCliente)
                            .addComponent(jLCpfCliente)
                            .addComponent(jLDataNascCliente)
                            .addComponent(jLCnpjCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JTFCnpjCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(JTFDataNascCliente)
                            .addComponent(JTFCpfCliente)
                            .addComponent(JTFTelCliente))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdCliente)
                    .addComponent(JTFIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeCliente)
                    .addComponent(JTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndCliente)
                    .addComponent(JTFEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumCliente)
                    .addComponent(JTFNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLComEndCliente)
                    .addComponent(JTFComEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBairroCliente)
                    .addComponent(JTFBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCidadeCliente)
                    .addComponent(JTFCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUfCliente)
                    .addComponent(JTFUfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCepCliente)
                    .addComponent(JTFCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelCliente)
                    .addComponent(JTFTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCpfCliente)
                    .addComponent(JTFCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataNascCliente)
                    .addComponent(JTFDataNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCnpjCliente)
                    .addComponent(JTFCnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeClienteActionPerformed


    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
                String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao)){
            //criar o objeto dados_cliente
            Cliente dados_cliente = new Cliente();
            // Atribuir os dados da tela no novo objeto
            dados_cliente.setId_cli(Integer.parseInt(JTFIdCliente.getText()));
            dados_cliente.setNome_cli(JTFNomeCliente.getText());
            dados_cliente.setEnde_cli(JTFEndCliente.getText());
            dados_cliente.setNume_cli(JTFNumCliente.getText());
            dados_cliente.setCompl_cli(JTFComEndCliente.getText());
            dados_cliente.setBair_cli(JTFBairroCliente.getText());
            dados_cliente.setCida_cli(JTFCidadeCliente.getText());
            dados_cliente.setUf_cli(JTFUfCliente.getText());
            dados_cliente.setCep_cli(JTFCepCliente.getText());
            dados_cliente.setFone_cli(JTFTelCliente.getText());
            dados_cliente.setCpf_cli(JTFCpfCliente.getText());
            dados_cliente.setDataNasc_cli(JTFDataNascCliente.getText());
            dados_cliente.setCnpj_cli(JTFCnpjCliente.getText());

            ConnectDAO objcon = new ConnectDAO();

            objcon.insereRegistroJFBD("CLIENTES", dados_cliente.dadosSQLValues());

            JTFIdCliente.setText("");
            JTFNomeCliente.setText("");
            JTFEndCliente.setText("");
            JTFNumCliente.setText("");
            JTFComEndCliente.setText("");
            JTFBairroCliente.setText("");
            JTFCidadeCliente.setText("");
            JTFUfCliente.setText("");
            JTFCepCliente.setText("");
            JTFTelCliente.setText("");
            JTFCpfCliente.setText("");     
            JTFDataNascCliente.setText("");
            JTFCnpjCliente.setText("");   
        }  
        
        Cliente cliente_tela = new Cliente();
        operacao = "Alteracao";
        if (operacaoAtivaGlobal.equals(operacao)){
        ConnectDAO objcon = new ConnectDAO();
        Cliente dados_cliente = new Cliente();
            dados_cliente.setId_cli(Integer.parseInt(JTFIdCliente.getText()));
            dados_cliente.setNome_cli(JTFNomeCliente.getText());
            dados_cliente.setEnde_cli(JTFEndCliente.getText());
            dados_cliente.setNume_cli(JTFNumCliente.getText());
            dados_cliente.setCompl_cli(JTFComEndCliente.getText());
            dados_cliente.setBair_cli(JTFBairroCliente.getText());
            dados_cliente.setCida_cli( JTFCidadeCliente.getText());
            dados_cliente.setUf_cli(JTFUfCliente.getText());
            dados_cliente.setCep_cli(JTFCepCliente.getText());
            dados_cliente.setFone_cli(JTFTelCliente.getText());
            dados_cliente.setCpf_cli(JTFCpfCliente.getText());
            dados_cliente.setDataNasc_cli(JTFDataNascCliente.getText());
            dados_cliente.setCnpj_cli(JTFCnpjCliente.getText());
            
            objcon.alteraRegistroJFBD("CLIENTES",dados_cliente.alteraDadosSQLValues(),"ID_CLI = " +JTFIdCliente.getText());
            
            JTFIdCliente.setText("");
            JTFNomeCliente.setText("");
            JTFEndCliente.setText("");
            JTFNumCliente.setText("");
            JTFComEndCliente.setText("");
            JTFBairroCliente.setText("");
            JTFCidadeCliente.setText("");
            JTFUfCliente.setText("");
            JTFCepCliente.setText("");
            JTFTelCliente.setText("");
            JTFCpfCliente.setText("");
            JTFDataNascCliente.setText("");
            JTFCnpjCliente.setText("");
        }
        
        //Agencias agencia_tela = new Agencias();
        operacao = "Alterar";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ConnectDAO objcon = new ConnectDAO();
            cliente_tela = objcon.pesquisaClienteJFBD("CLIENTES","ID_CLI = '" +JTFIdCliente.getText()+ "'");
           
            
            JTFIdCliente.setText(Integer.toString(cliente_tela.getId_cli()));
            JTFNomeCliente.setText(cliente_tela.getNome_cli());
            JTFEndCliente.setText(cliente_tela.getEnde_cli());
            JTFNumCliente.setText(cliente_tela.getNume_cli());
            JTFComEndCliente.setText(cliente_tela.getCompl_cli());
            JTFBairroCliente.setText(cliente_tela.getBair_cli());
            JTFCidadeCliente.setText(cliente_tela. getCida_cli());
            JTFUfCliente.setText(cliente_tela.getUf_cli());
            JTFCepCliente.setText(cliente_tela.getCep_cli());
            JTFTelCliente.setText(cliente_tela.getFone_cli());
            JTFCpfCliente.setText(cliente_tela.getCpf_cli());
            JTFDataNascCliente.setText(cliente_tela.getDataNasc_cli());
            JTFCnpjCliente.setText(cliente_tela.getCnpj_cli());
            
           
            JTFIdCliente.setVisible(true);
            JTFNomeCliente.setVisible(true);        
            JTFEndCliente.setVisible(true);        
            JTFNumCliente.setVisible(true);        
            JTFComEndCliente.setVisible(true);
            JTFBairroCliente.setVisible(true);        
            JTFCidadeCliente.setVisible(true);        
            JTFUfCliente.setVisible(true);        
            JTFCepCliente.setVisible(true);
            JTFTelCliente.setVisible(true);
            JTFCpfCliente.setVisible(true);
            JTFDataNascCliente.setVisible(true);
            JTFCnpjCliente.setVisible(true);
            

            
            jLIdCliente.setVisible(true);
            jLBairroCliente.setVisible(true);
            jLCepCliente.setVisible(true);
            jLCidadeCliente.setVisible(true);
            jLComEndCliente.setVisible(true);
            jLCpfCliente.setVisible(true);
            jLDataNascCliente.setVisible(true);
            jLEndCliente.setVisible(true);
            jLNomeCliente.setVisible(true);
            jLNumCliente.setVisible(true);
            jLTelCliente.setVisible(true);
            jLUfCliente.setVisible(true);
            
            
            jBConfirmar.setText("Alterar registro");
                  
            operacaoAtivaGlobal = "Alteracao";        
        }
        
        operacao = "Consultado";
        if (operacaoAtivaGlobal.equals(operacao)) {
            this.dispose();
        }
        
        
        
        operacao = "Excluido";
        if (operacaoAtivaGlobal.equals(operacao)) {
            int resposta = JOptionPane.showConfirmDialog(
            this, 
             "Tem certeza que deseja excluir esse Registro?", 
             "Confirmação", 
               JOptionPane.YES_NO_OPTION
            );
 
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFBD("CLIENTES","ID_CLI = '" +JTFIdCliente.getText()+ "'");
                JOptionPane.showMessageDialog(this, "Registro excluído!");
                this.dispose();
            } else {
                this.dispose();
            }
        }
        
        String operacao1 = "Excluir";
        String operacao2 = "Consultar";
        
        
        if (operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2)) {
            ConnectDAO objcon = new ConnectDAO();
            cliente_tela = objcon.pesquisaClienteJFBD("CLIENTES","ID_CLI = '" +JTFIdCliente.getText()+ "'");
           
            
            JTFIdCliente.setText(Integer.toString(cliente_tela.getId_cli()));
            JTFNomeCliente.setText(cliente_tela.getNome_cli());
            JTFEndCliente.setText(cliente_tela.getEnde_cli());
            JTFNumCliente.setText(cliente_tela.getNume_cli());
            JTFComEndCliente.setText(cliente_tela.getCompl_cli());
            JTFBairroCliente.setText(cliente_tela.getBair_cli());
            JTFCidadeCliente.setText(cliente_tela. getCida_cli());
            JTFUfCliente.setText(cliente_tela.getUf_cli());
            JTFCepCliente.setText(cliente_tela.getCep_cli());
            JTFTelCliente.setText(cliente_tela.getFone_cli());
            JTFCpfCliente.setText(cliente_tela.getCpf_cli());
            JTFDataNascCliente.setText(cliente_tela.getDataNasc_cli());
            JTFCnpjCliente.setText(cliente_tela.getCnpj_cli());
            
            JTFIdCliente.setVisible(true);
            JTFNomeCliente.setVisible(true);        
            JTFEndCliente.setVisible(true);        
            JTFNumCliente.setVisible(true);        
            JTFComEndCliente.setVisible(true);
            JTFBairroCliente.setVisible(true);        
            JTFCidadeCliente.setVisible(true);        
            JTFUfCliente.setVisible(true);        
            JTFCepCliente.setVisible(true);
            JTFTelCliente.setVisible(true);
            JTFCpfCliente.setVisible(true);
            JTFDataNascCliente.setVisible(true);
            JTFCnpjCliente.setVisible(true);     
            
            
            JTFIdCliente.setEditable(false);
            JTFNomeCliente.setEditable(false);        
            JTFEndCliente.setEditable(false);        
            JTFNumCliente.setEditable(false);        
            JTFComEndCliente.setEditable(false);
            JTFBairroCliente.setEditable(false);        
            JTFCidadeCliente.setEditable(false);        
            JTFUfCliente.setEditable(false);        
            JTFCepCliente.setEditable(false);
            JTFTelCliente.setEditable(false);
            JTFCpfCliente.setEditable(false);
            JTFDataNascCliente.setEditable(false);
            JTFCnpjCliente.setEditable(false);     
            

            jLIdCliente.setVisible(true);
            jLBairroCliente.setVisible(true);
            jLCepCliente.setVisible(true);
            jLCidadeCliente.setVisible(true);
            jLComEndCliente.setVisible(true);
            jLCpfCliente.setVisible(true);
            jLDataNascCliente.setVisible(true);
            jLEndCliente.setVisible(true);
            jLNomeCliente.setVisible(true);
            jLNumCliente.setVisible(true);
            jLTelCliente.setVisible(true);
            jLUfCliente.setVisible(true);
            jLCnpjCliente.setVisible(true);
            
            jBConfirmar.setText("Fechar");
                  
            if (operacaoAtivaGlobal.equals(operacao1)) {
            operacaoAtivaGlobal = "Excluido";
            jBConfirmar.setText("Excluir Registro");
            
            }
            else {
            operacaoAtivaGlobal = "Consultado";
            }        
        }
        
        
        
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectDAO objcon = new ConnectDAO();
        objcon.connectDB();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFBairroCliente;
    private javax.swing.JTextField JTFCepCliente;
    private javax.swing.JTextField JTFCidadeCliente;
    private javax.swing.JTextField JTFCnpjCliente;
    private javax.swing.JTextField JTFComEndCliente;
    private javax.swing.JTextField JTFCpfCliente;
    private javax.swing.JTextField JTFDataNascCliente;
    private javax.swing.JTextField JTFEndCliente;
    private javax.swing.JTextField JTFIdCliente;
    private javax.swing.JTextField JTFNomeCliente;
    private javax.swing.JTextField JTFNumCliente;
    private javax.swing.JTextField JTFTelCliente;
    private javax.swing.JTextField JTFUfCliente;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBairroCliente;
    private javax.swing.JLabel jLCepCliente;
    private javax.swing.JLabel jLCidadeCliente;
    private javax.swing.JLabel jLCnpjCliente;
    private javax.swing.JLabel jLComEndCliente;
    private javax.swing.JLabel jLCpfCliente;
    private javax.swing.JLabel jLDataNascCliente;
    private javax.swing.JLabel jLEndCliente;
    private javax.swing.JLabel jLIdCliente;
    private javax.swing.JLabel jLNomeCliente;
    private javax.swing.JLabel jLNumCliente;
    private javax.swing.JLabel jLTelCliente;
    private javax.swing.JLabel jLUfCliente;
    // End of variables declaration//GEN-END:variables
}
