/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import mvc_dao.ConnectDAO;
import Model.ContaCorrente;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class JFContaCorrente extends javax.swing.JFrame {

    /**
     * Creates new form JFContaCorrente
     */
    public JFContaCorrente() {
        initComponents();
    }

    String operacaoAtivaGlobal = "Nenhum";
    
    public JFContaCorrente(String operacaoGlobal) {
        initComponents();
        operacaoAtivaGlobal = operacaoGlobal;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            JFIdCli.setVisible(true);
            JFNumAge.setVisible(true);
            JFNumCC.setVisible(true);
            JFSaldo.setVisible(true);
            
            jLNumAge.setVisible(true);
            jLNumCc.setVisible(true);
            jLSaldo.setVisible(true);
            jLIdCli.setVisible(true);
            
            jBConfirmar.setText("Incluir registro");
    }
        operacaoAtivaGlobal = operacaoGlobal;
        
        String operacao1 = "Alterar";
        String operacao2 = "Consultar";
        String operacao3 = "Excluir";
        
        if(operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2) || operacaoAtivaGlobal.equals(operacao3)){
        
            JFIdCli.setVisible(false);
            JFNumAge.setVisible(false);
            JFNumCC.setVisible(true);
            JFSaldo.setVisible(false);
            
            jLIdCli.setVisible(false);
            jLNumAge.setVisible(false);
            jLNumCc.setVisible(true);
            jLSaldo.setVisible(false);
            
            
            jBConfirmar.setText("Pesquisar registro");
        
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIdCli = new javax.swing.JLabel();
        jLNumAge = new javax.swing.JLabel();
        jLNumCc = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        jBConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JFIdCli = new javax.swing.JTextField();
        JFNumAge = new javax.swing.JTextField();
        JFNumCC = new javax.swing.JTextField();
        JFSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLIdCli.setText("ID do cliente: ");

        jLNumAge.setText("Número da Agência: ");

        jLNumCc.setText("Número da Conta: ");

        jLSaldo.setText("Saldo: ");

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jButton1.setText("Testar Conexão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JFIdCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFIdCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLIdCli)
                            .addComponent(jLSaldo)
                            .addComponent(jLNumCc)
                            .addComponent(jLNumAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JFIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFNumAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumAge)
                    .addComponent(JFNumAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumCc)
                    .addComponent(JFNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdCli)
                    .addComponent(JFIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSaldo)
                    .addComponent(JFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao)){
            //criar o objeto dados_agencia
            ContaCorrente dados_contacorrente = new ContaCorrente();
            // Atribuir os dados da tela no novo objeto
            dados_contacorrente.setId_cli(Integer.parseInt(JFIdCli.getText()));
            dados_contacorrente.setNum_agencia(Integer.parseInt(JFNumAge.getText()));
            dados_contacorrente.setNum_cc(Integer.parseInt(JFNumCC.getText()));
            dados_contacorrente.setSaldo(Double.parseDouble(JFSaldo.getText()));
        
            ConnectDAO objcon = new ConnectDAO();

            objcon.insereRegistroJFBD("CONTACORRENTE", dados_contacorrente.dadosSQLValues());

            JFIdCli.setText("");
            JFNumAge.setText("");
            JFNumCC.setText("");
            JFSaldo.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_jBConfirmarActionPerformed
    
        ContaCorrente contacorrente_tela = new ContaCorrente();
        operacao = "Alteracao";
        if (operacaoAtivaGlobal.equals(operacao)){
        ConnectDAO objcon = new ConnectDAO();
        ContaCorrente dados_contacorrente = new ContaCorrente();
            dados_contacorrente.setNum_agencia(Integer.parseInt(JFNumAge.getText()));
            dados_contacorrente.setNum_cc(Integer.parseInt(JFNumCC.getText()));
            dados_contacorrente.setId_cli(Integer.parseInt(JFIdCli.getText()));
            dados_contacorrente. setSaldo(Double.parseDouble(JFSaldo.getText()));
            
            
            objcon.alteraRegistroJFBD("CONTACORRENTE",dados_contacorrente.alteraDadosSQLValues(),"NUM_CC = " +JFNumCC.getText());
            
            JFNumAge.setText("");
            JFNumCC.setText("");
            JFIdCli.setText("");            
            JFSaldo.setText("");
            
        }
        
        //Agencias agencia_tela = new Agencias();
        operacao = "Alterar";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ConnectDAO objcon = new ConnectDAO();
            contacorrente_tela = objcon.pesquisaContaCorrenteJFBD("CONTACORRENTE","NUM_CC = '" +JFNumCC.getText()+ "'");
           
            
            JFIdCli.setText(Integer.toString(contacorrente_tela.getId_cli()));
            JFNumAge.setText(Integer.toString(contacorrente_tela.getNum_agencia()));
            JFNumCC.setText(Integer.toString(contacorrente_tela.getNum_cc()));
            JFSaldo.setText(Double.toString(contacorrente_tela. getSaldo()));
            
            
           
            JFIdCli.setVisible(true);
            JFNumAge.setVisible(true);        
            JFNumCC.setVisible(true);        
            JFSaldo.setVisible(true);        
            
           
            jLIdCli.setVisible(true);
            jLNumAge.setVisible(true);
            jLNumCc.setVisible(true);
            jLSaldo.setVisible(true);
            
            
            
            jBConfirmar.setText("Alterar registro");
                  
            operacaoAtivaGlobal = "Alteracao";        
        }
        
        operacao = "Consultado";
        if (operacaoAtivaGlobal.equals(operacao)) {
            this.dispose();
        }
        
        operacao = "Excluido";
        if (operacaoAtivaGlobal.equals(operacao)) {
            int resposta = JOptionPane.showConfirmDialog(
            this, 
             "Tem certeza que deseja excluir esse Registro?", 
             "Confirmação", 
               JOptionPane.YES_NO_OPTION
            );
 
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFBD("CONTACORRENTE","NUM_CC = '" +JFNumCC.getText()+ "'");
                JOptionPane.showMessageDialog(this, "Registro excluído!");
                this.dispose();
            } else {
                this.dispose();
            }
        }
        
        String operacao1 = "Excluir";
        String operacao2 = "Consultar";
        
        
         if (operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2)) {
            ConnectDAO objcon = new ConnectDAO();
            contacorrente_tela = objcon.pesquisaContaCorrenteJFBD("CONTACORRENTE","NUM_CC = '" +JFNumCC.getText()+ "'");
            
            
            JFIdCli.setText(Integer.toString(contacorrente_tela.getId_cli()));
            JFNumAge.setText(Integer.toString(contacorrente_tela.getNum_agencia()));
            JFNumCC.setText(Integer.toString(contacorrente_tela.getNum_cc()));
            JFSaldo.setText(Double.toString(contacorrente_tela.getSaldo()));
            
            JFIdCli.setVisible(true);
            JFNumAge.setVisible(true);       
            JFNumCC.setVisible(true);       
            JFSaldo.setVisible(true);  
           
            JFIdCli.setEditable(false);
            JFNumAge.setEditable(false);        
            JFNumCC.setEditable(false);        
            JFSaldo.setEditable(false);        
            
            

            jLIdCli.setVisible(true);
            jLNumAge.setVisible(true);
            jLNumCc.setVisible(true);
            jLSaldo.setVisible(true);
            
            
            jBConfirmar.setText("Fechar");
                  
            if (operacaoAtivaGlobal.equals(operacao1)) {
            operacaoAtivaGlobal = "Excluido";
            jBConfirmar.setText("Excluir Registro");
            
            }
            else {
            operacaoAtivaGlobal = "Consultado";
            }              
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectDAO objcon = new ConnectDAO();
        objcon.connectDB();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JFIdCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFIdCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFIdCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFContaCorrente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JFIdCli;
    private javax.swing.JTextField JFNumAge;
    private javax.swing.JTextField JFNumCC;
    private javax.swing.JTextField JFSaldo;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLIdCli;
    private javax.swing.JLabel jLNumAge;
    private javax.swing.JLabel jLNumCc;
    private javax.swing.JLabel jLSaldo;
    // End of variables declaration//GEN-END:variables
}
