/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import mvc_dao.ConnectDAO;
import Model.Movimentacao;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class JFMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form JFMovimentacao
     */
    public JFMovimentacao() {
        initComponents();
    }

    String operacaoAtivaGlobal = "Nenhum";

    /* Create new form */
     public JFMovimentacao(String operacaoGlobal) {
        initComponents();
        operacaoAtivaGlobal = operacaoGlobal;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            JTFCompl_His.setVisible(true);
            JTFData_Mov.setVisible(true);
            JTFDebito_Credito.setVisible(true);
            JTFId_His.setVisible(true);
            JTFNum_Ag.setVisible(true);
            JTFNum_CC.setVisible(true);
            JTFNum_Doc.setVisible(true);
            JTFSaldo.setVisible(true);
            JTFValor.setVisible(true);
            
            jId_Historico.setVisible(true);
            jLCompl_Hist.setVisible(true);
            jLSaldo.setVisible(true);
            jLData_Mov.setVisible(true);
            jLDebito_Credito.setVisible(true);
            jLNum_Agencia.setVisible(true);
            jLNum_CC.setVisible(true);
            jLNum_Doc.setVisible(true);
            jLValor.setVisible(true);
            
            jBConfirmar.setText("Incluir registro");
    }
    
        operacaoAtivaGlobal = operacaoGlobal;
        
        String operacao1 = "Alterar";
        String operacao2 = "Consultar";
        String operacao3 = "Excluir";
        
        if(operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2) || operacaoAtivaGlobal.equals(operacao3)){
        
            JTFCompl_His.setVisible(false);
            JTFData_Mov.setVisible(false);
            JTFDebito_Credito.setVisible(false);
            JTFId_His.setVisible(false);
            JTFNum_Ag.setVisible(false);
            JTFNum_CC.setVisible(false);
            JTFNum_Doc.setVisible(true);
            JTFSaldo.setVisible(false);
            JTFValor.setVisible(false);
            
            jId_Historico.setVisible(false);
            jLCompl_Hist.setVisible(false);
            jLSaldo.setVisible(false);
            jLData_Mov.setVisible(false);
            jLDebito_Credito.setVisible(false);
            jLNum_Agencia.setVisible(false);
            jLNum_CC.setVisible(false);
            jLNum_Doc.setVisible(true);
            jLValor.setVisible(false);
            
            
            jBConfirmar.setText("Pesquisar registro");
        
        }
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNum_Agencia = new javax.swing.JLabel();
        jLNum_CC = new javax.swing.JLabel();
        jLData_Mov = new javax.swing.JLabel();
        jLNum_Doc = new javax.swing.JLabel();
        jLDebito_Credito = new javax.swing.JLabel();
        jId_Historico = new javax.swing.JLabel();
        jLCompl_Hist = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        JTFNum_Ag = new javax.swing.JTextField();
        JTFNum_CC = new javax.swing.JTextField();
        JTFData_Mov = new javax.swing.JTextField();
        JTFNum_Doc = new javax.swing.JTextField();
        JTFDebito_Credito = new javax.swing.JTextField();
        JTFId_His = new javax.swing.JTextField();
        JTFCompl_His = new javax.swing.JTextField();
        JTFValor = new javax.swing.JTextField();
        JTFSaldo = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNum_Agencia.setText("Número da Agência:");

        jLNum_CC.setText("Número da Conta Corrente:");

        jLData_Mov.setText("Data da Movimentação:");

        jLNum_Doc.setText("Número do Documento:");

        jLDebito_Credito.setText("Débito ou Crédito:");

        jId_Historico.setText("Id do Histórico:");
        jId_Historico.setToolTipText("");

        jLCompl_Hist.setText("Complemento Histórico:");

        jLValor.setText("Valor:");

        jLSaldo.setText("Saldo:");

        JTFData_Mov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFData_MovActionPerformed(evt);
            }
        });

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jButton1.setText("Testar Conexão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCompl_Hist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFCompl_His, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jId_Historico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFId_His, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLDebito_Credito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFDebito_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNum_Doc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFNum_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLData_Mov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFData_Mov, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNum_CC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(JTFNum_CC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNum_Agencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFNum_Ag, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum_Agencia)
                    .addComponent(JTFNum_Ag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum_CC)
                    .addComponent(JTFNum_CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLData_Mov)
                    .addComponent(JTFData_Mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum_Doc)
                    .addComponent(JTFNum_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDebito_Credito)
                    .addComponent(JTFDebito_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jId_Historico)
                    .addComponent(JTFId_His, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCompl_Hist)
                    .addComponent(JTFCompl_His, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValor)
                    .addComponent(JTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSaldo)
                    .addComponent(JTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFData_MovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFData_MovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFData_MovActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao)){
            //criar o objeto dados_cliente
            Movimentacao dados_movimentacao = new Movimentacao();
            // Atribuir os dados da tela no novo objeto
            dados_movimentacao.setNum_age(Integer.parseInt(JTFNum_Ag.getText()));
            dados_movimentacao.setNum_cc(Integer.parseInt (JTFNum_CC.getText()));
            dados_movimentacao.setData_mov(JTFData_Mov.getText());
            dados_movimentacao.setNum_docto(JTFNum_Doc.getText());
            dados_movimentacao.setDebito_credito (JTFDebito_Credito.getText().charAt(0));
            dados_movimentacao.setId_his(Integer.parseInt (JTFId_His.getText()));
            dados_movimentacao.setCompl_his(JTFCompl_His.getText());
            dados_movimentacao.setValor(Double.parseDouble(JTFValor.getText()));
            dados_movimentacao.setSaldo(Double.parseDouble(JTFSaldo.getText()));
            
            ConnectDAO objcon = new ConnectDAO();

            objcon.insereRegistroJFBD("MOVIMENTACAO", dados_movimentacao.dadosSQLValues());
            
            JTFNum_Ag.setText("");
            JTFNum_CC.setText("");
            JTFData_Mov.setText("");
            JTFNum_Doc.setText("");
            JTFDebito_Credito.setText("");
            JTFId_His.setText("");
            JTFCompl_His.setText("");
            JTFValor.setText("");
            JTFSaldo.setText("");
        }    
        Movimentacao movimentacao_tela = new Movimentacao();
        operacao = "Alteracao";
        if (operacaoAtivaGlobal.equals(operacao)){
        ConnectDAO objcon = new ConnectDAO();
        Movimentacao dados_movimentacao = new Movimentacao();
            dados_movimentacao.setNum_age(Integer.parseInt(JTFNum_Ag.getText()));
            dados_movimentacao.setNum_cc(Integer.parseInt (JTFNum_CC.getText()));
            dados_movimentacao.setData_mov(JTFData_Mov.getText());
            dados_movimentacao.setNum_docto(JTFNum_Doc.getText());
            dados_movimentacao.setDebito_credito (JTFDebito_Credito.getText().charAt(0));
            dados_movimentacao.setId_his(Integer.parseInt (JTFId_His.getText()));
            dados_movimentacao.setCompl_his(JTFCompl_His.getText());
            dados_movimentacao.setValor(Double.parseDouble (JTFValor.getText()));
            dados_movimentacao.setSaldo(Double.parseDouble (JTFSaldo.getText()));
            
            
            objcon.alteraRegistroJFBD("MOVIMENTACAO",dados_movimentacao.alteraDadosSQLValues(),"NUM_DOCTO = '" +JTFNum_Doc.getText() +"'");
            
            JTFNum_Ag.setText("");
            JTFNum_CC.setText("");
            JTFData_Mov.setText("");            
            JTFNum_Doc.setText("");
            JTFDebito_Credito.setText("");
            JTFId_His.setText("");
            JTFCompl_His.setText("");
            JTFValor.setText("");
            JTFSaldo.setText("");
            
        } 
        
        operacao = "Alterar";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ConnectDAO objcon = new ConnectDAO();
            movimentacao_tela = objcon.pesquisaMovimentacaoJFBD("MOVIMENTACAO","NUM_DOCTO = '" +JTFNum_Doc.getText()+ "'");
           
            
            JTFNum_Ag.setText(Integer.toString(movimentacao_tela.getNum_age()));
            JTFNum_CC.setText(Integer.toString(movimentacao_tela.getNum_cc()));
            JTFData_Mov.setText(movimentacao_tela.getData_mov());
            JTFNum_Doc.setText(movimentacao_tela. getNum_docto());
            JTFDebito_Credito.setText(Character.toString(movimentacao_tela. getDebito_credito()));
            JTFId_His.setText(Integer.toString(movimentacao_tela. getId_his()));
            JTFCompl_His.setText(movimentacao_tela. getCompl_his());
            JTFValor.setText(Double.toString(movimentacao_tela. getValor()));
            JTFSaldo.setText(Double.toString(movimentacao_tela. getSaldo()));
            
            
           
            JTFNum_Ag.setVisible(true);
            JTFNum_CC.setVisible(true);        
            JTFData_Mov.setVisible(true);        
            JTFNum_Doc.setVisible(true);
            JTFDebito_Credito.setVisible(true);
            JTFId_His.setVisible(true);
            JTFCompl_His.setVisible(true);
            JTFValor.setVisible(true);
            JTFSaldo.setVisible(true);
            
           
           jId_Historico.setVisible(true);
           jLCompl_Hist.setVisible(true);
           jLData_Mov.setVisible(true);
           jLDebito_Credito.setVisible(true);
           jLNum_Agencia.setVisible(true);
           jLNum_CC.setVisible(true);
           jLNum_Doc.setVisible(true);
           jLSaldo.setVisible(true);
           jLValor.setVisible(true);
            
            
            
            jBConfirmar.setText("Alterar registro");
                  
            operacaoAtivaGlobal = "Alteracao";        
        }
        
        operacao = "Consultado";
        if (operacaoAtivaGlobal.equals(operacao)) {
            this.dispose();
        }
        
        
        operacao = "Excluido";
        if (operacaoAtivaGlobal.equals(operacao)) {
            int resposta = JOptionPane.showConfirmDialog(
            this, 
             "Tem certeza que deseja excluir esse Registro?", 
             "Confirmação", 
               JOptionPane.YES_NO_OPTION
            );
 
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFBD("MOVIMENTACAO","NUM_DOCTO = '" +JTFNum_Doc.getText()+ "'");
                JOptionPane.showMessageDialog(this, "Registro excluído!");
                this.dispose();
            } else {
                this.dispose();
            }
        }
        
        String operacao1 = "Excluir";
        String operacao2 = "Consultar";
        
        
        if (operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2)) {
            ConnectDAO objcon = new ConnectDAO();
            movimentacao_tela = objcon.pesquisaMovimentacaoJFBD("MOVIMENTACAO","NUM_DOCTO = '" +JTFNum_Doc.getText()+ "'");
            
            
            JTFNum_Ag.setText(Integer.toString(movimentacao_tela.getNum_age()));
            JTFNum_CC.setText(Integer.toString(movimentacao_tela.getNum_cc()));
            JTFData_Mov.setText(movimentacao_tela.getData_mov());
            JTFNum_Doc.setText(movimentacao_tela. getNum_docto());
            JTFDebito_Credito.setText(Character.toString(movimentacao_tela. getDebito_credito()));
            JTFId_His.setText(Integer.toString(movimentacao_tela. getId_his()));
            JTFCompl_His.setText(movimentacao_tela. getCompl_his());
            JTFValor.setText(Double.toString(movimentacao_tela. getValor()));
            JTFSaldo.setText(Double.toString(movimentacao_tela. getSaldo()));
            
            JTFNum_Ag.setVisible(true);
            JTFNum_CC.setVisible(true);       
            JTFData_Mov.setVisible(true);        
            JTFNum_Doc.setVisible(true);
            JTFDebito_Credito.setVisible(true);
            JTFId_His.setVisible(true);
            JTFCompl_His.setVisible(true);
            JTFValor.setVisible(true);
            JTFSaldo.setVisible(true);
           
            JTFNum_Ag.setEditable(false);
            JTFNum_CC.setEditable(false);        
            JTFData_Mov.setEditable(false);        
            JTFNum_Doc.setEditable(false);
            JTFDebito_Credito.setEditable(false);
            JTFId_His.setEditable(false);
            JTFCompl_His.setEditable(false);
            JTFValor.setEditable(false);
            JTFSaldo.setEditable(false);
            
            
            

           jId_Historico.setVisible(true);
           jLCompl_Hist.setVisible(true);
           jLData_Mov.setVisible(true);
           jLDebito_Credito.setVisible(true);
           jLNum_Agencia.setVisible(true);
           jLNum_CC.setVisible(true);
           jLNum_Doc.setVisible(true);
           jLSaldo.setVisible(true);
           jLValor.setVisible(true);
            
            
            
            jBConfirmar.setText("Fechar");
                  
            if (operacaoAtivaGlobal.equals(operacao1)) {
            operacaoAtivaGlobal = "Excluido";
            jBConfirmar.setText("Excluir Registro");
            
            }
            else {
            operacaoAtivaGlobal = "Consultado";
            }                
        }
        
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConnectDAO objcon = new ConnectDAO();
        objcon.connectDB();  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCompl_His;
    private javax.swing.JTextField JTFData_Mov;
    private javax.swing.JTextField JTFDebito_Credito;
    private javax.swing.JTextField JTFId_His;
    private javax.swing.JTextField JTFNum_Ag;
    private javax.swing.JTextField JTFNum_CC;
    private javax.swing.JTextField JTFNum_Doc;
    private javax.swing.JTextField JTFSaldo;
    private javax.swing.JTextField JTFValor;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jId_Historico;
    private javax.swing.JLabel jLCompl_Hist;
    private javax.swing.JLabel jLData_Mov;
    private javax.swing.JLabel jLDebito_Credito;
    private javax.swing.JLabel jLNum_Agencia;
    private javax.swing.JLabel jLNum_CC;
    private javax.swing.JLabel jLNum_Doc;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLValor;
    // End of variables declaration//GEN-END:variables
}

