/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import mvc_dao.ConnectDAO;
import Model.Usuario;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class JFUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JFUsuario
     */
    public JFUsuario() {
        initComponents();
    }

    String operacaoAtivaGlobal = "Nenhum";

    /* Create new form */
     public JFUsuario(String operacaoGlobal) {
        initComponents();
        operacaoAtivaGlobal = operacaoGlobal;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            JTFId.setVisible(true);
            JTFNum_AG.setVisible(true);
            JTFNum_CC.setVisible(true);
            JTFSenha.setVisible(true);
            
            jLId.setVisible(true);
            jLNum_AG.setVisible(true);
            jLNum_CC.setVisible(true);
            jLSenha.setVisible(true);
            
            
            jBConfirmar.setText("Incluir registro");
    }
    
        operacaoAtivaGlobal = operacaoGlobal;
        
        String operacao1 = "Alterar";
        String operacao2 = "Consultar";
        String operacao3 = "Excluir";
        
         if(operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2) || operacaoAtivaGlobal.equals(operacao3)){
        
            JTFId.setVisible(true);
            JTFNum_AG.setVisible(false);
            JTFNum_CC.setVisible(false);
            JTFSenha.setVisible(false);
            
            jLId.setVisible(true);
            jLNum_AG.setVisible(false);
            jLNum_CC.setVisible(false);
            jLSenha.setVisible(false);
            
            
            jBConfirmar.setText("Pesquisar registro");
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLId = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jLNum_AG = new javax.swing.JLabel();
        jLNum_CC = new javax.swing.JLabel();
        JTFId = new javax.swing.JTextField();
        JTFSenha = new javax.swing.JTextField();
        JTFNum_AG = new javax.swing.JTextField();
        JTFNum_CC = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLId.setText("Id:");

        jLSenha.setText("Senha:");

        jLNum_AG.setText("Número da Agência:");

        jLNum_CC.setText("Número da Conta Corrente:");

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jButton1.setText("Testar Conexão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLId)
                            .addComponent(jLSenha)
                            .addComponent(jLNum_AG)
                            .addComponent(jLNum_CC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFNum_AG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFNum_CC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLId)
                    .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSenha)
                    .addComponent(JTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum_AG)
                    .addComponent(JTFNum_AG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum_CC)
                    .addComponent(JTFNum_CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao)){
            //criar o objeto dados_cliente
            Usuario dados_usuario = new Usuario();
            // Atribuir os dados da tela no novo objeto
            dados_usuario.setId (JTFId.getText());
            dados_usuario.setSenha(JTFSenha.getText());
            dados_usuario.setNum_age(Integer.parseInt (JTFNum_AG.getText()));
            dados_usuario.setNum_cc(Integer.parseInt (JTFNum_CC.getText()));
            
            ConnectDAO objcon = new ConnectDAO();

            objcon.insereRegistroJFBD("USUARIOS", dados_usuario.dadosSQLValues());
            
            JTFId.setText("");
            JTFSenha.setText("");
            JTFNum_AG.setText("");
            JTFNum_CC.setText("");
        }  
        
        Usuario usuario_tela = new Usuario();
        operacao = "Alteracao";
        if (operacaoAtivaGlobal.equals(operacao)){
        ConnectDAO objcon = new ConnectDAO();
        Usuario dados_usuario = new Usuario();
        
            dados_usuario.setId(JTFId.getText());
            dados_usuario.setNum_age(Integer.parseInt(JTFNum_AG.getText()));
            dados_usuario.setNum_cc(Integer.parseInt(JTFNum_CC.getText()));
            dados_usuario.setSenha(JTFSenha.getText());
            
            
            objcon.alteraRegistroJFBD("USUARIOS",dados_usuario.alteraDadosSQLValues(),"ID = '" +JTFId.getText() +"'");
            
            JTFId.setText("");
            JTFNum_AG.setText("");
            JTFNum_CC.setText("");            
            JTFSenha.setText("");
            
        }
        operacao = "Alterar";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ConnectDAO objcon = new ConnectDAO();
            usuario_tela = objcon.pesquisaUsuarioJFBD("USUARIOS","ID = '" +JTFId.getText()+ "'");
           
            
            JTFId.setText(usuario_tela.getId());
            JTFNum_AG.setText(Integer.toString(usuario_tela.getNum_age()));
            JTFNum_CC.setText(Integer.toString(usuario_tela.getNum_cc()));
            JTFSenha.setText(usuario_tela.getSenha());
            
            
           
            JTFId.setVisible(true);
            JTFNum_AG.setVisible(true);        
            JTFNum_CC.setVisible(true);        
            JTFSenha.setVisible(true);        
            
            JTFId.setEditable(false); 
            JTFNum_AG.setEditable(false); 
            JTFNum_CC.setEditable(false); 
           
            jLId.setVisible(true);
            jLNum_AG.setVisible(true);
            jLNum_CC.setVisible(true);
            jLSenha.setVisible(true);
            
            
            
            jBConfirmar.setText("Alterar registro");
                  
            operacaoAtivaGlobal = "Alteracao";        
        }
        
        operacao = "Consultado";
        if (operacaoAtivaGlobal.equals(operacao)) {
            this.dispose();
        }
        
        operacao = "Excluido";
        if (operacaoAtivaGlobal.equals(operacao)) {
            int resposta = JOptionPane.showConfirmDialog(
            this, 
             "Tem certeza que deseja excluir esse Registro?", 
             "Confirmação", 
               JOptionPane.YES_NO_OPTION
            );
 
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFBD("USUARIOS","ID = '" +JTFId.getText()+ "'");
                JOptionPane.showMessageDialog(this, "Registro excluído!");
                this.dispose();
            } else {
                this.dispose();
            }
        }
        
        String operacao1 = "Excluir";
        String operacao2 = "Consultar";
        
        
        if (operacaoAtivaGlobal.equals(operacao1) || operacaoAtivaGlobal.equals(operacao2)) {
            ConnectDAO objcon = new ConnectDAO();
            usuario_tela = objcon.pesquisaUsuarioJFBD("USUARIOS","ID = '" +JTFId.getText()+ "'");
            
            
            JTFId.setText(usuario_tela.getId());
            JTFNum_AG.setText(Integer.toString(usuario_tela.getNum_age()));
            JTFNum_CC.setText(Integer.toString(usuario_tela.getNum_cc()));
            JTFSenha.setText(usuario_tela.getSenha());
            
            JTFId.setVisible(true);
            JTFNum_AG.setVisible(true);       
            JTFNum_CC.setVisible(true);      
            JTFSenha.setVisible(true);   
           
            JTFId.setEditable(false);
            JTFNum_AG.setEditable(false);        
            JTFNum_CC.setEditable(false);        
            JTFSenha.setEditable(false);        
            
            

            jLId.setVisible(true);
            jLNum_AG.setVisible(true);
            jLNum_CC.setVisible(true);
            jLSenha.setVisible(true);
            
            
            jBConfirmar.setText("Fechar");
                  
            if (operacaoAtivaGlobal.equals(operacao1)) {
            operacaoAtivaGlobal = "Excluido";
            jBConfirmar.setText("Excluir Registro");
            
            }
            else {
            operacaoAtivaGlobal = "Consultado";
            }                
              
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConnectDAO objcon = new ConnectDAO();
        objcon.connectDB();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFId;
    private javax.swing.JTextField JTFNum_AG;
    private javax.swing.JTextField JTFNum_CC;
    private javax.swing.JTextField JTFSenha;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLNum_AG;
    private javax.swing.JLabel jLNum_CC;
    private javax.swing.JLabel jLSenha;
    // End of variables declaration//GEN-END:variables
}
